(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function navButton(label,href,cls){const b=document.createElement('button');b.type='button';b.className='nav '+(cls||'');b.textContent=label;b.onclick=()=>location.href=href;return b}
function normalizeNav(){const side=$('.side');if(!side)return;$$('.nav',side).forEach(b=>{const t=(b.textContent||'').toLowerCase();if(t.includes('pokédex kanto')||t.includes('pokedex kanto')||t.trim()==='🔴 kanto'){b.textContent='🔴 Pokédex Completa';b.classList.add('odtcg-highlight');b.onclick=()=>location.href='pokedex.html'}if(t.includes('vendas')){b.textContent='💰 Vendas';b.classList.add('odtcg-sales');b.onclick=()=>location.href='vendas.html'}})}
function addNav(){const side=$('.side');if(!side)return;const buttons=$$('.nav',side);const minhas=buttons.find(b=>/minhas\s+cartas/i.test(b.textContent||''));const insert=(key,label,href)=>{if(side.querySelector('[data-odtcg="'+key+'"]'))return;const b=navButton(label,href);b.dataset.odtcg=key;if(minhas&&minhas.parentNode)minhas.insertAdjacentElement('afterend',b);else side.appendChild(b)};insert('cards','🃏 Cartas TCG','cartas.html');insert('search','🔎 Busca Universal','busca.html');insert('decks','🧠 Análise de Deck','decks.html')}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function dashboardStyle(){if(document.getElementById('odtcg-finance-style'))return;const s=document.createElement('style');s.id='odtcg-finance-style';s.textContent=`.odtcg-finance{margin:0 0 18px;background:linear-gradient(135deg,#4b1707,#250a04);border:2px solid #9b4813;border-radius:15px;padding:16px;box-shadow:0 8px 22px #0008}.odtcg-finance h2{margin:0 0 4px;color:#fff4dc;font-size:20px}.odtcg-finance p{margin:0 0 13px;color:#d7a66d;font-size:12px}.odtcg-finance-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.odtcg-finance-card{background:linear-gradient(180deg,#421707,#260a04);border:1px solid #8f410f;border-radius:11px;padding:12px}.odtcg-finance-card small{display:block;color:#d7a66d;font-weight:700}.odtcg-finance-card strong{display:block;margin-top:4px;color:#fff0cf;font-size:20px}.odtcg-finance-profit strong{color:#8fe69a}.odtcg-finance-foot{margin-top:12px;display:flex;justify-content:space-between;gap:10px;align-items:center;color:#d7a66d;font-size:11px}.odtcg-finance-link{border:1px solid #ffc62b;background:#321006;color:#ffe8bd;border-radius:8px;padding:7px 10px;text-decoration:none;font-weight:900}.odtcg-finance-error{color:#ffb4a1}.odtcg-finance-loading{opacity:.75}@media(max-width:900px){.odtcg-finance-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:500px){.odtcg-finance-grid{grid-template-columns:1fr 1fr}.odtcg-finance-card strong{font-size:16px}.odtcg-finance-foot{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(s)}
function monthRange(){const d=new Date();const start=new Date(d.getFullYear(),d.getMonth(),1);const next=new Date(d.getFullYear(),d.getMonth()+1,1);return {start:start.toISOString().slice(0,10),next:next.toISOString().slice(0,10)}}
async function loadFinance(){if(location.pathname.endsWith('vendas.html'))return;const anchor=$('.titleRow')||$('.title')||$('.content');if(!anchor||document.getElementById('odtcg-finance'))return;dashboardStyle();const box=document.createElement('section');box.id='odtcg-finance';box.className='odtcg-finance';box.innerHTML='<h2>💰 Resumo financeiro</h2><p>Visão rápida das vendas deste mês.</p><div class="odtcg-finance-grid"><div class="odtcg-finance-card"><small>Faturamento</small><strong id="odf-revenue">Carregando...</strong></div><div class="odtcg-finance-card"><small>Custo das cartas</small><strong id="odf-cost">Carregando...</strong></div><div class="odtcg-finance-card odtcg-finance-profit"><small>Lucro estimado</small><strong id="odf-profit">Carregando...</strong></div><div class="odtcg-finance-card"><small>Cartas vendidas</small><strong id="odf-qty">—</strong></div></div><div class="odtcg-finance-foot"><span id="odf-status">Consultando vendas...</span><a class="odtcg-finance-link" href="vendas.html">Ver vendas →</a></div>';anchor.insertAdjacentElement('afterend',box);try{const range=monthRange();const url='https://txhktdwwxjdswtedupud.supabase.co/rest/v1/vendas?select=valor_total,custo_total,quantidade,data_venda&data_venda=gte.'+range.start+'&data_venda=lt.'+range.next+'&order=data_venda.desc';const key='sb_publishable_odjEzAe1A-F4ur1PsXIuRA_qomQzX44';const r=await fetch(url,{headers:{apikey:key,Authorization:'Bearer '+key}});if(!r.ok)throw new Error('Não foi possível consultar as vendas');const rows=await r.json();const revenue=rows.reduce((a,s)=>a+Number(s.valor_total||0),0);const cost=rows.reduce((a,s)=>a+Number(s.custo_total||0),0);const qty=rows.reduce((a,s)=>a+Number(s.quantidade||0),0);$('#odf-revenue').textContent=money(revenue);$('#odf-cost').textContent=money(cost);$('#odf-profit').textContent=money(revenue-cost);$('#odf-qty').textContent=qty+' un.';$('#odf-status').textContent=rows.length+' venda(s) registrada(s) neste mês';}catch(e){$('#odf-status').textContent='Não foi possível carregar os dados financeiros.';$('#odf-status').classList.add('odtcg-finance-error')}}
function run(){normalizeNav();addNav();document.documentElement.dataset.odtcgTheme='firered-gba';setTimeout(loadFinance,120)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,50));else setTimeout(run,50);window.addEventListener('load',()=>setTimeout(run,100));
})();
